### ISSUE TITLE
Support reverse lookup

### ISSUE THREAD

**Issue by jessgusclark** [rsksmart/rns-resolver.js#12]
Support the `reverse` function allowing the search of an address to resolve to a domain name. This should be simple to accomidate, add the abi method, the method, and tests.

**Comment by hugomarti** [comment]
we need a way to input the wallet address from a user in the frontend and get returned the domain name, so we can send it to the smart contract to do the verification.

**Comment by jessgusclark** [comment]
@hugomarti yes, that user story would be complete with the closing of this issue.
